// Auto-generated by agent_hub.typegen.export

// Do not edit manually.


export type CLISessionSourceType = "Claw" | "CLI";

export type CodeChangeToolType = "edit" | "write" | "multi_edit";

export type DiffMode = "unstaged" | "staged" | "branch";

export type OrchestrationStatus = "pending" | "running" | "completed" | "failed";

export type ProjectFramework = "vite" | "nextjs" | "create_react_app" | "angular" | "vue_cli" | "astro" | "static_html" | "unknown";

export type SearchMatchField = "slug" | "summary" | "path" | "git_branch" | "first_message";

export interface ActivityTypeAssistantMessage {
  kind: "assistant_message";
}

export interface ActivityTypeThinking {
  kind: "thinking";
}

export interface ActivityTypeToolResult {
  kind: "tool_result";
  name: string;
  success: boolean;
}

export interface ActivityTypeToolUse {
  kind: "tool_use";
  name: string;
}

export interface ActivityTypeUserMessage {
  kind: "user_message";
}

export interface CodeChangeInput {
  tool_type: CodeChangeToolType;
  file_path: string;
  old_string?: string;
  new_string?: string;
  replace_all?: boolean;
  edits?: EditEntry[];
}

export interface EditEntry {
  old_string?: string;
  new_string?: string;
}

export interface ActivityEntry {
  id?: string;
  timestamp: string;
  type: ActivityTypeToolUse | ActivityTypeToolResult | ActivityTypeUserMessage | ActivityTypeAssistantMessage | ActivityTypeThinking;
  description?: string;
  tool_input?: CodeChangeInput | null;
}

export interface CLILoadingStateAddingRepository {
  kind: "adding_repository";
  name: string;
}

export interface CLILoadingStateDetectingWorktrees {
  kind: "detecting_worktrees";
}

export interface CLILoadingStateIdle {
  kind: "idle";
}

export interface CLILoadingStateRefreshing {
  kind: "refreshing";
}

export interface CLILoadingStateRestoringMonitoredSessions {
  kind: "restoring_monitored_sessions";
}

export interface CLILoadingStateRestoringRepositories {
  kind: "restoring_repositories";
}

export interface CLILoadingStateScanningSessionsState {
  kind: "scanning_sessions";
}

export interface CLISession {
  id: string;
  project_path: string;
  branch_name?: string | null;
  is_worktree?: boolean;
  last_activity_at: string;
  message_count?: number;
  is_active?: boolean;
  first_message?: string;
  last_message?: string;
  slug?: string;
  session_file_path?: string;
  needs_attention?: string | null;
}

export interface CLISessionGroup {
  project_path: string;
  project_name: string;
  sessions?: CLISession[];
  is_worktree?: boolean;
  main_repo_path?: string;
}

export interface ClientMessageRefreshSessions {
  kind: "refresh_sessions";
}

export interface ClientMessageSubscribeSession {
  kind: "subscribe_session";
  session_id: string;
  project_path: string;
  session_file_path: string;
}

export interface ClientMessageTerminalInput {
  kind: "terminal_input";
  session_key: string;
  data: string;
}

export interface ClientMessageTerminalResize {
  kind: "terminal_resize";
  session_key: string;
  cols: number;
  rows: number;
}

export interface ClientMessageUnsubscribeSession {
  kind: "unsubscribe_session";
  session_id: string;
}

export interface FileOperation {
  id?: string;
  timestamp: string;
  input: CodeChangeInput;
}

export interface ConsolidatedFileChange {
  id?: string;
  file_path: string;
  operations?: FileOperation[];
  first_timestamp: string;
  last_timestamp: string;
}

export interface CostBreakdown {
  input_cost: number;
  output_cost: number;
  cache_read_cost: number;
  cache_creation_cost: number;
}

export interface DailyActivity {
  date: string;
  message_count?: number;
  session_count?: number;
  tool_call_count?: number;
}

export interface DailyModelTokens {
  date: string;
  tokens_by_model?: Record<string, number>;
}

export interface DetectedProject {
  framework: ProjectFramework;
  command: string;
  arguments?: string[];
  default_port?: number;
  readiness_patterns?: string[];
}

export interface DevServerStateDetecting {
  kind: "detecting";
}

export interface DevServerStateFailed {
  kind: "failed";
  error: string;
}

export interface DevServerStateIdle {
  kind: "idle";
}

export interface DevServerStateReady {
  kind: "ready";
  url: string;
}

export interface DevServerStateStarting {
  kind: "starting";
  message?: string;
}

export interface DevServerStateStopping {
  kind: "stopping";
}

export interface DevServerStateWaitingForReady {
  kind: "waiting_for_ready";
}

export interface DiffComment {
  id?: string;
  timestamp: string;
  file_path: string;
  line_number: number;
  side: "left" | "right" | "unified";
  line_content?: string;
  text?: string;
}

export interface GitDiffFileEntry {
  id?: string;
  file_path: string;
  relative_path: string;
  additions?: number;
  deletions?: number;
}

export interface GitDiffState {
  files?: GitDiffFileEntry[];
}

export interface LongestSession {
  session_id: string;
  duration: number;
  message_count: number;
  timestamp: string;
}

export interface ModelUsage {
  input_tokens?: number;
  output_tokens?: number;
  cache_read_input_tokens?: number;
  cache_creation_input_tokens?: number;
  web_search_requests?: number;
  cost_usd?: number;
}

export interface GlobalStatsCache {
  version?: number;
  last_computed_date?: string;
  daily_activity?: DailyActivity[];
  daily_model_tokens?: DailyModelTokens[] | null;
  model_usage?: Record<string, ModelUsage>;
  total_sessions?: number;
  total_messages?: number;
  longest_session?: LongestSession | null;
  first_session_date?: string | null;
  hour_counts?: Record<string, number> | null;
}

export interface HistoryEntry {
  display: string;
  timestamp: number;
  project: string;
  session_id: string;
}

export interface MermaidDiagramInfo {
  source: string;
  file_path?: string;
  timestamp?: string;
}

export interface OrchestrationSession {
  id?: string;
  worktree_path: string;
  prompt: string;
  status?: OrchestrationStatus;
}

export interface OrchestrationPlan {
  id?: string;
  name: string;
  sessions?: OrchestrationSession[];
  created_at?: string;
}

export interface ParsedFileDiff {
  file_path: string;
  old_content?: string;
  new_content?: string;
}

export interface WorktreeBranch {
  name: string;
  path: string;
  is_worktree?: boolean;
  sessions?: CLISession[];
  is_expanded?: boolean;
}

export interface PendingHubSession {
  id?: string;
  worktree: WorktreeBranch;
  started_at?: string;
  initial_prompt?: string;
  initial_input_text?: string;
  dangerously_skip_permissions?: boolean;
  worktree_name?: string;
}

export interface PendingToolUse {
  tool_name: string;
  tool_use_id: string;
  timestamp: string;
  input_str?: string;
  code_change_input?: CodeChangeInput | null;
}

export interface PlanInfo {
  file_path: string;
  content: string;
  timestamp?: string;
}

export interface PlanState {
  file_path: string;
}

export interface RemoteBranch {
  name: string;
  remote: string;
}

export interface SelectedRepository {
  path: string;
  name: string;
  worktrees?: WorktreeBranch[];
  is_expanded?: boolean;
}

export interface ServerMessageError {
  kind: "error";
  message: string;
}

export interface SessionSearchResult {
  id: string;
  slug?: string;
  project_path?: string;
  git_branch?: string;
  first_message?: string;
  summaries?: string[];
  last_activity_at: string;
  matched_field: SearchMatchField;
  matched_text?: string;
  relevance_score?: number;
}

export interface ServerMessageSearchResults {
  kind: "search_results";
  results?: SessionSearchResult[];
}

export interface SessionMonitorState {
  status?: SessionStatusThinking | SessionStatusExecutingTool | SessionStatusWaitingForUser | SessionStatusAwaitingApproval | SessionStatusAwaitingQuestion | SessionStatusIdle;
  current_tool?: string;
  last_activity_at?: string;
  input_tokens?: number;
  output_tokens?: number;
  total_output_tokens?: number;
  cache_read_tokens?: number;
  cache_creation_tokens?: number;
  message_count?: number;
  tool_calls?: Record<string, number>;
  session_started_at?: string;
  model?: string;
  git_branch?: string;
  pending_tool_use?: PendingToolUse | null;
  recent_activities?: ActivityEntry[];
  has_mermaid_content?: boolean;
  plan_file_path?: string;
  plan_content?: string;
  plans?: PlanInfo[];
  mermaid_diagrams?: MermaidDiagramInfo[];
}

export interface SessionStatusAwaitingApproval {
  kind: "awaiting_approval";
  tool: string;
}

export interface SessionStatusAwaitingQuestion {
  kind: "awaiting_question";
}

export interface SessionStatusExecutingTool {
  kind: "executing_tool";
  name: string;
}

export interface SessionStatusIdle {
  kind: "idle";
}

export interface SessionStatusThinking {
  kind: "thinking";
}

export interface SessionStatusWaitingForUser {
  kind: "waiting_for_user";
}

export interface SessionHistoryEntry {
  line: number;
  type: string;
  data: Record<string, unknown>;
}

export interface ServerMessageSessionHistoryAppend {
  kind: "session_history_append";
  session_id: string;
  entries: SessionHistoryEntry[];
  total_lines: number;
}

export interface ServerMessageSessionStateUpdate {
  kind: "session_state_update";
  session_id: string;
  state: SessionMonitorState;
}

export interface ServerMessageSessionsUpdated {
  kind: "sessions_updated";
  repositories?: SelectedRepository[];
}

export interface ServerMessageStatsUpdated {
  kind: "stats_updated";
  provider: string;
  stats: GlobalStatsCache;
}

export interface ServerMessageTerminalOutput {
  kind: "terminal_output";
  session_key: string;
  data: string;
}

export interface SessionIndexEntry {
  session_id: string;
  project_path: string;
  slug?: string;
  git_branch?: string;
  first_message?: string;
  summaries?: string[];
  last_activity_at: string;
}

export interface WorktreeCreationProgressCompleted {
  kind: "completed";
  path: string;
}

export interface WorktreeCreationProgressFailed {
  kind: "failed";
  error: string;
}

export interface WorktreeCreationProgressIdle {
  kind: "idle";
}

export interface WorktreeCreationProgressPreparing {
  kind: "preparing";
  message?: string;
}

export interface WorktreeCreationProgressUpdatingFiles {
  kind: "updating_files";
  current: number;
  total: number;
}

export type ActivityType =
  | ActivityTypeToolUse
  | ActivityTypeToolResult
  | ActivityTypeUserMessage
  | ActivityTypeAssistantMessage
  | ActivityTypeThinking;

export type CLILoadingState =
  | CLILoadingStateIdle
  | CLILoadingStateRestoringRepositories
  | CLILoadingStateRestoringMonitoredSessions
  | CLILoadingStateAddingRepository
  | CLILoadingStateDetectingWorktrees
  | CLILoadingStateScanningSessionsState
  | CLILoadingStateRefreshing;

export type ClientMessage =
  | ClientMessageSubscribeSession
  | ClientMessageUnsubscribeSession
  | ClientMessageTerminalInput
  | ClientMessageTerminalResize
  | ClientMessageRefreshSessions;

export type DevServerState =
  | DevServerStateIdle
  | DevServerStateDetecting
  | DevServerStateStarting
  | DevServerStateWaitingForReady
  | DevServerStateReady
  | DevServerStateFailed
  | DevServerStateStopping;

export type ServerMessage =
  | ServerMessageSessionStateUpdate
  | ServerMessageSessionsUpdated
  | ServerMessageStatsUpdated
  | ServerMessageSearchResults
  | ServerMessageTerminalOutput
  | ServerMessageSessionHistoryAppend
  | ServerMessageError;

export type SessionStatus =
  | SessionStatusThinking
  | SessionStatusExecutingTool
  | SessionStatusWaitingForUser
  | SessionStatusAwaitingApproval
  | SessionStatusAwaitingQuestion
  | SessionStatusIdle;

export type WorktreeCreationProgress =
  | WorktreeCreationProgressIdle
  | WorktreeCreationProgressPreparing
  | WorktreeCreationProgressUpdatingFiles
  | WorktreeCreationProgressCompleted
  | WorktreeCreationProgressFailed;
